# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.history_tree = QtGui.QTreeWidget(self.centralwidget)
        self.history_tree.setRootIsDecorated(True)
        self.history_tree.setHeaderHidden(True)
        self.history_tree.setObjectName(_fromUtf8("history_tree"))
        self.history_tree.headerItem().setText(0, _fromUtf8("1"))
        self.horizontalLayout_4.addWidget(self.history_tree)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_18.addWidget(self.label_19)
        self.acft_comboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acft_comboBox.sizePolicy().hasHeightForWidth())
        self.acft_comboBox.setSizePolicy(sizePolicy)
        self.acft_comboBox.setObjectName(_fromUtf8("acft_comboBox"))
        self.verticalLayout_18.addWidget(self.acft_comboBox)
        self.horizontalLayout_8.addLayout(self.verticalLayout_18)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_16.addWidget(self.label_18)
        self.activity_comboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activity_comboBox.sizePolicy().hasHeightForWidth())
        self.activity_comboBox.setSizePolicy(sizePolicy)
        self.activity_comboBox.setObjectName(_fromUtf8("activity_comboBox"))
        self.verticalLayout_16.addWidget(self.activity_comboBox)
        self.horizontalLayout_8.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_17.addWidget(self.label_17)
        self.activity_edit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activity_edit.sizePolicy().hasHeightForWidth())
        self.activity_edit.setSizePolicy(sizePolicy)
        self.activity_edit.setObjectName(_fromUtf8("activity_edit"))
        self.verticalLayout_17.addWidget(self.activity_edit)
        self.horizontalLayout_8.addLayout(self.verticalLayout_17)
        self.verticalLayout_15.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.add_activity_btn = QtGui.QPushButton(self.centralwidget)
        self.add_activity_btn.setObjectName(_fromUtf8("add_activity_btn"))
        self.horizontalLayout_6.addWidget(self.add_activity_btn)
        self.verticalLayout_15.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6.addLayout(self.verticalLayout_15)
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.verticalLayout_6.addWidget(self.dateEdit)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_6.addWidget(self.label_14)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.blue_pc_edit = QtGui.QLineEdit(self.centralwidget)
        self.blue_pc_edit.setObjectName(_fromUtf8("blue_pc_edit"))
        self.verticalLayout_2.addWidget(self.blue_pc_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.red_pc_edit = QtGui.QLineEdit(self.centralwidget)
        self.red_pc_edit.setObjectName(_fromUtf8("red_pc_edit"))
        self.verticalLayout_3.addWidget(self.red_pc_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.yellow_pc_edit = QtGui.QLineEdit(self.centralwidget)
        self.yellow_pc_edit.setObjectName(_fromUtf8("yellow_pc_edit"))
        self.verticalLayout_4.addWidget(self.yellow_pc_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.green_pc_edit = QtGui.QLineEdit(self.centralwidget)
        self.green_pc_edit.setObjectName(_fromUtf8("green_pc_edit"))
        self.verticalLayout_5.addWidget(self.green_pc_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_6.addWidget(self.label_15)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_7.addWidget(self.label_6)
        self.blue_weight_edit = QtGui.QLineEdit(self.centralwidget)
        self.blue_weight_edit.setObjectName(_fromUtf8("blue_weight_edit"))
        self.verticalLayout_7.addWidget(self.blue_weight_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.red_weight_edit = QtGui.QLineEdit(self.centralwidget)
        self.red_weight_edit.setObjectName(_fromUtf8("red_weight_edit"))
        self.verticalLayout_8.addWidget(self.red_weight_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_9.addWidget(self.label_8)
        self.yellow_weight_edit = QtGui.QLineEdit(self.centralwidget)
        self.yellow_weight_edit.setObjectName(_fromUtf8("yellow_weight_edit"))
        self.verticalLayout_9.addWidget(self.yellow_weight_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_10.addWidget(self.label_9)
        self.green_weight_edit = QtGui.QLineEdit(self.centralwidget)
        self.green_weight_edit.setObjectName(_fromUtf8("green_weight_edit"))
        self.verticalLayout_10.addWidget(self.green_weight_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_6.addWidget(self.label_16)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_11.addWidget(self.label_10)
        self.blue_tab_edit = QtGui.QLineEdit(self.centralwidget)
        self.blue_tab_edit.setObjectName(_fromUtf8("blue_tab_edit"))
        self.verticalLayout_11.addWidget(self.blue_tab_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_12.addWidget(self.label_11)
        self.red_tab_edit = QtGui.QLineEdit(self.centralwidget)
        self.red_tab_edit.setObjectName(_fromUtf8("red_tab_edit"))
        self.verticalLayout_12.addWidget(self.red_tab_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_13.addWidget(self.label_12)
        self.yellow_tab_edit = QtGui.QLineEdit(self.centralwidget)
        self.yellow_tab_edit.setObjectName(_fromUtf8("yellow_tab_edit"))
        self.verticalLayout_13.addWidget(self.yellow_tab_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_14.addWidget(self.label_13)
        self.green_tab_edit = QtGui.QLineEdit(self.centralwidget)
        self.green_tab_edit.setObjectName(_fromUtf8("green_tab_edit"))
        self.verticalLayout_14.addWidget(self.green_tab_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.run_counter = QtGui.QSpinBox(self.centralwidget)
        self.run_counter.setObjectName(_fromUtf8("run_counter"))
        self.horizontalLayout_7.addWidget(self.run_counter)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.add_changes_btn = QtGui.QPushButton(self.centralwidget)
        self.add_changes_btn.setObjectName(_fromUtf8("add_changes_btn"))
        self.horizontalLayout_5.addWidget(self.add_changes_btn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_19.setText(_translate("MainWindow", "ACFT:", None))
        self.label_18.setText(_translate("MainWindow", "Activity", None))
        self.label_17.setText(_translate("MainWindow", "New Activity", None))
        self.add_activity_btn.setText(_translate("MainWindow", "Add Activity", None))
        self.label_14.setText(_translate("MainWindow", "PC Links", None))
        self.label_2.setText(_translate("MainWindow", "Blue", None))
        self.label_3.setText(_translate("MainWindow", "Red", None))
        self.label_4.setText(_translate("MainWindow", "Yellow", None))
        self.label_5.setText(_translate("MainWindow", "Green", None))
        self.label_15.setText(_translate("MainWindow", "Weights", None))
        self.label_6.setText(_translate("MainWindow", "Blue", None))
        self.label_7.setText(_translate("MainWindow", "Red", None))
        self.label_8.setText(_translate("MainWindow", "Yellow", None))
        self.label_9.setText(_translate("MainWindow", "Green", None))
        self.label_16.setText(_translate("MainWindow", "Tabs", None))
        self.label_10.setText(_translate("MainWindow", "Blue", None))
        self.label_11.setText(_translate("MainWindow", "Red", None))
        self.label_12.setText(_translate("MainWindow", "Yellow", None))
        self.label_13.setText(_translate("MainWindow", "Green", None))
        self.label.setText(_translate("MainWindow", "Run", None))
        self.add_changes_btn.setText(_translate("MainWindow", "Add Changes", None))

