# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.history_tree = QtWidgets.QTreeWidget(self.centralwidget)
        self.history_tree.setObjectName("history_tree")
        self.history_tree.headerItem().setText(0, "1")
        self.horizontalLayout_4.addWidget(self.history_tree)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_15.addWidget(self.label_17)
        self.activity_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.activity_comboBox.setObjectName("activity_comboBox")
        self.verticalLayout_15.addWidget(self.activity_comboBox)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_15.addWidget(self.label)
        self.activity_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.activity_edit.setObjectName("activity_edit")
        self.verticalLayout_15.addWidget(self.activity_edit)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.add_activity_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_activity_btn.setObjectName("add_activity_btn")
        self.horizontalLayout_6.addWidget(self.add_activity_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_15.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6.addLayout(self.verticalLayout_15)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_6.addWidget(self.dateEdit)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.blue_pc_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.blue_pc_edit.setObjectName("blue_pc_edit")
        self.verticalLayout_2.addWidget(self.blue_pc_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.red_pc_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.red_pc_edit.setObjectName("red_pc_edit")
        self.verticalLayout_3.addWidget(self.red_pc_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.yellow_pc_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.yellow_pc_edit.setObjectName("yellow_pc_edit")
        self.verticalLayout_4.addWidget(self.yellow_pc_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.green_pc_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.green_pc_edit.setObjectName("green_pc_edit")
        self.verticalLayout_5.addWidget(self.green_pc_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.blue_weight_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.blue_weight_edit.setObjectName("blue_weight_edit")
        self.verticalLayout_7.addWidget(self.blue_weight_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.red_weight_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.red_weight_edit.setObjectName("red_weight_edit")
        self.verticalLayout_8.addWidget(self.red_weight_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.yellow_weight_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.yellow_weight_edit.setObjectName("yellow_weight_edit")
        self.verticalLayout_9.addWidget(self.yellow_weight_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.green_weight_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.green_weight_edit.setObjectName("green_weight_edit")
        self.verticalLayout_10.addWidget(self.green_weight_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.blue_tab_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.blue_tab_edit.setObjectName("blue_tab_edit")
        self.verticalLayout_11.addWidget(self.blue_tab_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.red_tab_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.red_tab_edit.setObjectName("red_tab_edit")
        self.verticalLayout_12.addWidget(self.red_tab_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12)
        self.yellow_tab_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.yellow_tab_edit.setObjectName("yellow_tab_edit")
        self.verticalLayout_13.addWidget(self.yellow_tab_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_14.addWidget(self.label_13)
        self.green_tab_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.green_tab_edit.setObjectName("green_tab_edit")
        self.verticalLayout_14.addWidget(self.green_tab_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.run_counter = QtWidgets.QSpinBox(self.centralwidget)
        self.run_counter.setObjectName("run_counter")
        self.horizontalLayout_7.addWidget(self.run_counter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.add_changes_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_changes_btn.setObjectName("add_changes_btn")
        self.horizontalLayout_5.addWidget(self.add_changes_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_17.setText(_translate("MainWindow", "Activity"))
        self.label.setText(_translate("MainWindow", "New Activity"))
        self.add_activity_btn.setText(_translate("MainWindow", "Add Activity"))
        self.label_14.setText(_translate("MainWindow", "PC Links"))
        self.label_2.setText(_translate("MainWindow", "Blue"))
        self.label_3.setText(_translate("MainWindow", "Red"))
        self.label_4.setText(_translate("MainWindow", "Yellow"))
        self.label_5.setText(_translate("MainWindow", "Green"))
        self.label_15.setText(_translate("MainWindow", "Weights"))
        self.label_6.setText(_translate("MainWindow", "Blue"))
        self.label_7.setText(_translate("MainWindow", "Red"))
        self.label_8.setText(_translate("MainWindow", "Yellow"))
        self.label_9.setText(_translate("MainWindow", "Green"))
        self.label_16.setText(_translate("MainWindow", "Tabs"))
        self.label_10.setText(_translate("MainWindow", "Blue"))
        self.label_11.setText(_translate("MainWindow", "Red"))
        self.label_12.setText(_translate("MainWindow", "Yellow"))
        self.label_13.setText(_translate("MainWindow", "Green"))
        self.add_changes_btn.setText(_translate("MainWindow", "Add Changes"))

