exercises_hood = {
    'wall ball': 3,
    'thrusters': 6,
    'power clean': 3,
    'dead lift': 4,
    'snatches': 7,
    'pull up': 2,
    'ctp-up': 3,
    'chin-up': 2,
    'back squat': 3,
    'front squats': 5,
    'air squats': 1,
    'burpies': 8,
    'hand stand push up': 8,
    'push-up': 1,
    'muscle-up': 10,
    'hang clean': 6,
    'high hang clean': 7,
    'run': 8,
    'kettle-bell': 4,
    'double-under': 3,
    'push press': 7,
    'split jerk': 7,
    'over head squat': 9,
    'push jerk': 6,
    'squat clean': 8,
    'squat snatch': 8,
    'sit ups': 1,
    'ghd sit up': 2,
    'dips': 4,
    'toes to bar': 5,
    'knees to elbow': 3}

exercises_zach = {
    'wall ball': 3,
    'thrusters': 4,
    'power clean': 5,
    'dead lift': 4,
    'snatches': 3,
    'pull up': 2,
    'ctp-up': 3,
    'chin-up': 2,
    'back squat': 3,
    'front squats': 4,
    'air squats': 1,
    'burpies': 1,
    'hand stand push up': 2,
    'push-up': 1,
    'muscle-up': 6,
    'hang clean': 5,
    'high hang clean': 6,
    'run': 5,
    'kettle-bell': 2,
    'double-under': 2,
    'push press': 3,
    'split jerk': 7,
    'over head squat': 6,
    'push jerk': 4,
    'squat clean': 7,
    'squat snatch': 8,
    'sit ups': 1,
    'ghd sit up': 4,
    'dips': 3,
    'toes to bar': 2,
    'knees to elbow': 1}

# exercises_werner = {
# 'wall ball': ,
# 'thrusters': ,
# 'power clean': ,
# 'dead lift': ,
# 'snatches': ,
# 'pull up': ,
# 'ctp-up': ,
# 'chin-up': ,
# 'back squat': ,
# 'front squats': ,
# 'air squats': ,
# 'burpies': ,
# 'hand stand push up': ,
# 'push-up': ,
# 'muscle-up': ,
# 'hang clean': ,
# 'high hang clean': ,
# 'run': ,
# 'kettle-bell': ,
# 'double-under': ,
# 'push press': ,
# 'split jerk': ,
# 'over head squat': ,
# 'push jerk': ,
# 'squat clean': ,
# 'squat snatch': ,
# 'sit ups': ,
# 'ghd sit up': ,
# 'dips': ,
# 'toes to bar': ,
# 'knees to elbow': }

exercises_rhea = {
    'wall ball': 3,
    'thrusters': 6,
    'power clean': 3,
    'dead lift': 8,
    'snatches': 4,
    'pull up': 5,
    'ctp-up': 8,
    'chin-up': 4,
    'back squat': 4,
    'front squats': 6,
    'air squats': 1,
    'burpies': 2,
    'hand stand push up': 5,
    'push-up': 1,
    'muscle-up': 10,
    'hang clean': 2,
    'high hang clean': 2,
    'run': 6,
    'kettle-bell': 1,
    'double-under': 1,
    'push press': 4,
    'split jerk': 8,
    'over head squat': 6,
    'push jerk': 5,
    'squat clean': 5,
    'squat snatch': 5,
    'sit ups': 1,
    'ghd sit up': 3,
    'dips': 3,
    'toes to bar': 7,
    'knees to elbow': 1}

exercises_strider = {
    'wall ball': 4,
    'thrusters': 7,
    'power clean': 4,
    'dead lift': 2,
    'snatches': 6,
    'pull up': 6,
    'ctp-up': 2,
    'chin-up': 2,
    'back squat': 5,
    'front squats': 8,
    'air squats': 1,
    'burpies': 9,
    'hand stand push up': 9,
    'push-up': 3,
    'muscle-up': 10,
    'hang clean': 4,
    'high hang clean': 7,
    'run': 6,
    'kettle-bell': 2,
    'double-under': 5,
    'push press': 6,
    'split jerk': 4,
    'over head squat': 9,
    'push jerk': 5,
    'squat clean': 6,
    'squat snatch': 6,
    'sit ups': 1,
    'ghd sit up': 3,
    'dips': 1,
    'toes to bar': 4,
    'knees to elbow': 2}

exercises_kyle = {
    'wall ball': 1,
    'thrusters': 8,
    'power clean': 5,
    'dead lift': 5,
    'snatches': 8,
    'pull up': 10,
    'ctp-up': 10,
    'chin-up': 5,
    'back squat': 3,
    'front squats': 7,
    'air squats': 5,
    'burpies': 7,
    'hand stand push up': 5,
    'push-up': 5,
    'muscle-up': 10,
    'hang clean': 5,
    'high hang clean': 6,
    'run': 5,
    'kettle-bell': 5,
    'double-under': 5,
    'push press': 3,
    'split jerk': 5,
    'over head squat': 10,  # no
    'push jerk': 4,
    'squat clean': 5,
    'squat snatch': 8,
    'sit ups': 6,
    'ghd sit up': 8,
    'dips': 7,
    'toes to bar': 7,
    'knees to elbow': 6}

exercises_casey = {
    'wall ball': 1,
    'thrusters': 2,
    'power clean': 3,
    'dead lift': 3,
    'snatches': 5,
    'pull up': 5,
    'ctp-up': 7,
    'chin-up': 2,
    'back squat': 2,
    'front squats': 3,
    'air squats': 1,
    'burpies': 2,
    'hand stand push up': 5,
    'push-up': 1,
    'muscle-up': 10,
    'hang clean': 3,
    'high hang clean': 3,
    'run': 6,
    'kettle-bell': 1,
    'double-under': 1,
    'push press': 2,
    'split jerk': 3,
    'over head squat': 4,
    'push jerk': 3,
    'squat clean': 5,
    'squat snatch': 4,
    'sit ups': 1,
    'ghd sit up': 2,
    'dips': 6,
    'toes to bar': 7,
    'knees to elbow': 3}


# exercises_bradley = {
# 'wall ball': ,
# 'thrusters': ,
# 'power clean': ,
# 'dead lift': ,
# 'snatches': ,
# 'pull up': ,
# 'ctp-up': ,
# 'chin-up': ,
# 'back squat': ,
# 'front squats': ,
# 'air squats': ,
# 'burpies': ,
# 'hand stand push up': ,
# 'push-up': ,
# 'muscle-up': ,
# 'hang clean': ,
# 'high hang clean': ,
# 'run': ,
# 'kettle-bell': ,
# 'double-under': ,
# 'push press': ,
# 'split jerk': ,
# 'over head squat': ,
# 'push jerk': ,
# 'squat clean': ,
# 'squat snatch': ,
# 'sit ups': ,
# 'ghd sit up': ,
# 'dips': ,
# 'toes to bar': ,
# 'knees to elbow': }

def score(ex_dict, exercise, reps, rounds=1):
    total_score = 0
    weight = ex_dict[exercise]
    for i in range(rounds):
        if i != 0:
            weight += weight
        rounds_score = reps * weight
        total_score += rounds_score

    return total_score  # (reps * rounds) + weight  # ((weight * reps) ** rounds)/1000


exercises = [
    'wall ball',
    'thrusters',
    'power clean',
    'dead lift',
    'snatches',
    'pull up',
    'ctp-up',
    'chin-up',
    'back squat',
    'front squats',
    'air squats',
    'burpies',
    'hand stand push up',
    'push-up',
    'muscle-up',
    'hang clean',
    'high hang clean',
    'run',
    'kettle-bell',
    'double-under',
    'push press',
    'split jerk',
    'over head squat',
    'push jerk',
    'squat clean',
    'squat snatch',
    'sit ups',
    'ghd sit up',
    'dips',
    'toes to bar',
    'knees to elbow']
temp = []
players = [exercises_casey, exercises_hood, exercises_kyle, exercises_rhea, exercises_strider, exercises_zach]
for key in exercises_zach.keys():
    temp.append(key)

# exercises.append(temp)
for p in players:
    ex = []
    for key in p:
        ex.append((key, p[key]))
    exercises.append(ex)

for i in exercises:
    print(i)

ball = score(exercises_rhea,'wall ball', 30, 3)
clean = score(exercises_rhea,'power clean', 30, 3)
run = score(exercises_rhea, 'run', 4, 3)
print(ball)
print(clean)
print(run)
print(ball + clean + run)