exercises_zach = {
    'wall ball': 3,
    'thrusters': 4,
    'power clean': 5,
    'dead lift': 4,
    'snatches': 3,
    'pull up': 2,
    'ctp-up': 3,
    'chin-up': 2,
    'back squat': 3,
    'front squats': 4,
    'air squats': 1,
    'burpies': 1,
    'hand stand push up': 2,
    'push-up': 1,
    'muscle-up': 6,
    'hang clean': 5,
    'high hang clean': 6,
    'run': 5,
    'kettle-bell': 2,
    'double-under': 2,
    'push press': 3,
    'split jerk': 7,
    'over head squat': 6,
    'push jerk': 4,
    'squat clean': 7,
    'squat snatch': 8,
    'sit ups': 1,
    'ghd sit up': 4,
    'dips': 3,
    'toes to bar': 2,
    'knees to elbow': 1}

categories = {'back & bi' : ['thrusters'], 'chest & tri' : [], 'legs' : ['wall ball''thrusters''power clean'], 'shoulders' : ['thrusters'], 'core': ['power clean']}
workout_groups = ['chippers', 'tabata', 'couplets', '6-9-12-9-6', 'triplets', '21-15-9']
